server:
  port: 8080
  context-path:  /

spring:
  mvc:
    static-path-pattern: /static/**
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://120.78.148.229:3306/youku_info?characterEncoding=utf8&useSSL=true
    username: user_youku_crawler
    password: hzhssg123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
